#!/usr/bin/env python

from __future__ import print_function

import fileinput
import os
import re
import sys

def is_header_incl(line):
    return re.match(r'^\s*#include\s*"(.+)"', line)

# Try to match the filename against a header-include regex
for fmatch in map(is_header_incl, fileinput.input()):
    if not fmatch: continue
    
    # extract filename from regex matched string
    filename, = fmatch.groups()
    
    print(filename)